const defaultMonster = {
  name: "",
  tokenSize: "",
  type: "",
  alignment: "",
  armorClass: "",
  hitPoints: "",
  hitDice: "",
  speed: { walk: "", fly: "", swim: "", climb: "", burrow: "" },
  abilityScores: { str: "", dex: "", con: "", int: "", wis: "", cha: "" },
  savingThrows: {},
  skills: {},
  damageVulnerabilities: [],
  damageResistances: [],
  damageImmunities: [],
  conditionImmunities: [],
  senses: {
    darkvision: "",
    blindsight: "",
    tremorsense: "",
    truesight: "",
    passivePerception: "",
  },
  languages: "",
  challengeRating: "",
  proficiencyBonus: "",
  traits: [],
  actions: [],
  reactions: [],
  legendaryResistances: [],
  legendaryActions: [],
  lairActions: [],
  regionalEffects: [],
  description: "",
  image: "",
  extraSections: [],
  campaigns: [],
};

export default defaultMonster;
